DROP TABLE IF EXISTS EMPLOYEES;

CREATE TABLE EMPLOYEES
(
    ID            SERIAL PRIMARY KEY,
    EMPLOYEE_CODE VARCHAR(100) NOT NULL UNIQUE,
    DOCUMENT      VARCHAR(11)  NOT NULL,
    FULL_NAME     VARCHAR(255) NOT NULL,
    DEPARTMENT    VARCHAR(100),
    CREATED_AT    TIMESTAMP
);