DROP TABLE IF EXISTS EMPLOYEES;
DROP TABLE IF EXISTS WORKING_HOURS;

CREATE TABLE EMPLOYEES
(
    ID            SERIAL PRIMARY KEY,
    EMPLOYEE_CODE VARCHAR(100) NOT NULL UNIQUE,
    DOCUMENT      VARCHAR(11)  NOT NULL,
    FULL_NAME     VARCHAR(255) NOT NULL,
    DEPARTMENT    VARCHAR(100),
    CREATED_AT    TIMESTAMP
);

CREATE TABLE WORKING_HOURS
(
    ID               SERIAL PRIMARY KEY,
    EMPLOYEE_CODE    VARCHAR(100) NOT NULL,
    WORK_DATE        DATE,
    CLOCK_IN_TIME    TIME,
    CLOCK_OUT_TIME   TIME,
    HOURS_WORKED     NUMERIC(5, 2),
    LUNCH_BREAK_START TIME,
    LUNCH_BREAK_END   TIME,
    LUNCH_BREAK_TIME NUMERIC(5, 2)
);